#!/bin/bash
#
# Simple AOSP wrapper to run commands in an AOSP docker container
#
# Author: Kyle Manna <kyle@kylemanna.com>
#

set -e

# Override from environment
AOSP_IMAGE=${AOSP_IMAGE:-kylemanna/aosp}
AOSP_VOL=${AOSP_VOL:-/vol0}
AOSP_ARGS=${AOSP_ARGS:---rm -it}
AOSP_VOL_AOSP=${AOSP_VOL_AOSP:-$AOSP_VOL/aosp}
AOSP_VOL_CCACHE=${AOSP_VOL_CCACHE:-$AOSP_VOL/ccache}

if [ ! -d "$AOSP_VOL_AOSP" -o ! -d "$AOSP_VOL_CCACHE" ]; then
    sudo mkdir -p $AOSP_VOL_AOSP $AOSP_VOL_CCACHE
    sudo chmod 777 $AOSP_VOL_AOSP $AOSP_VOL_CCACHE
fi

if [ -n "$SSH_AUTH_SOCK" ]; then
    SSH_AUTH_ARGS="-v $SSH_AUTH_SOCK:/tmp/ssh_auth -e SSH_AUTH_SOCK=/tmp/ssh_auth"
fi

docker run $AOSP_ARGS $SSH_AUTH_ARGS $AOSP_EXTRA_ARGS \
    -v "$AOSP_VOL_AOSP:/aosp" -v "$AOSP_VOL_CCACHE:/tmp/ccache" \
    $AOSP_IMAGE $@
